//go:build !codegen

// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package provider

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *Provider) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{164}); err != nil {
		return err
	}

	// t.Weight (int64) (int64)
	if len("weight") > 8192 {
		return xerrors.Errorf("Value in field \"weight\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("weight"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("weight")); err != nil {
		return err
	}

	if t.Weight >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Weight)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.Weight-1)); err != nil {
			return err
		}
	}

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return xerrors.Errorf("Value in field \"endpoint\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("endpoint"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("endpoint")); err != nil {
		return err
	}

	if len(t.Endpoint) > 8192 {
		return xerrors.Errorf("Value in field t.Endpoint was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Endpoint))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Endpoint)); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return xerrors.Errorf("Value in field \"provider\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("provider"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("provider")); err != nil {
		return err
	}

	if err := t.Provider.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.ReplicationWeight (int64) (int64)
	if len("replicationWeight") > 8192 {
		return xerrors.Errorf("Value in field \"replicationWeight\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("replicationWeight"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("replicationWeight")); err != nil {
		return err
	}

	if t.ReplicationWeight >= 0 {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.ReplicationWeight)); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajNegativeInt, uint64(-t.ReplicationWeight-1)); err != nil {
			return err
		}
	}

	return nil
}

func (t *Provider) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Provider{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("Provider: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 17)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Weight (int64) (int64)
		case "weight":
			{
				maj, extra, err := cr.ReadHeader()
				if err != nil {
					return err
				}
				var extraI int64
				switch maj {
				case cbg.MajUnsignedInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 positive overflow")
					}
				case cbg.MajNegativeInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 negative overflow")
					}
					extraI = -1 - extraI
				default:
					return fmt.Errorf("wrong type for int64 field: %d", maj)
				}

				t.Weight = int64(extraI)
			}
			// t.Endpoint (string) (string)
		case "endpoint":

			{
				sval, err := cbg.ReadStringWithMax(cr, 8192)
				if err != nil {
					return err
				}

				t.Endpoint = string(sval)
			}
			// t.Provider (did.DID) (struct)
		case "provider":

			{

				if err := t.Provider.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Provider: %w", err)
				}

			}
			// t.ReplicationWeight (int64) (int64)
		case "replicationWeight":
			{
				maj, extra, err := cr.ReadHeader()
				if err != nil {
					return err
				}
				var extraI int64
				switch maj {
				case cbg.MajUnsignedInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 positive overflow")
					}
				case cbg.MajNegativeInt:
					extraI = int64(extra)
					if extraI < 0 {
						return fmt.Errorf("int64 negative overflow")
					}
					extraI = -1 - extraI
				default:
					return fmt.Errorf("wrong type for int64 field: %d", maj)
				}

				t.ReplicationWeight = int64(extraI)
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *ListOK) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.Providers ([]provider.Provider) (slice)
	if len("providers") > 8192 {
		return xerrors.Errorf("Value in field \"providers\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("providers"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("providers")); err != nil {
		return err
	}

	if len(t.Providers) > 8192 {
		return xerrors.Errorf("Slice value in field t.Providers was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Providers))); err != nil {
		return err
	}
	for _, v := range t.Providers {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}
	return nil
}

func (t *ListOK) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ListOK{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ListOK: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 9)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Providers ([]provider.Provider) (slice)
		case "providers":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Providers: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Providers = make([]Provider, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						if err := t.Providers[i].UnmarshalCBOR(cr); err != nil {
							return xerrors.Errorf("unmarshaling t.Providers[i]: %w", err)
						}

					}

				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *RegisterArguments) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return xerrors.Errorf("Value in field \"endpoint\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("endpoint"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("endpoint")); err != nil {
		return err
	}

	if len(t.Endpoint) > 8192 {
		return xerrors.Errorf("Value in field t.Endpoint was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Endpoint))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Endpoint)); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return xerrors.Errorf("Value in field \"provider\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("provider"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("provider")); err != nil {
		return err
	}

	if err := t.Provider.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *RegisterArguments) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RegisterArguments{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("RegisterArguments: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Endpoint (string) (string)
		case "endpoint":

			{
				sval, err := cbg.ReadStringWithMax(cr, 8192)
				if err != nil {
					return err
				}

				t.Endpoint = string(sval)
			}
			// t.Provider (did.DID) (struct)
		case "provider":

			{

				if err := t.Provider.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Provider: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *DeregisterArguments) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return xerrors.Errorf("Value in field \"provider\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("provider"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("provider")); err != nil {
		return err
	}

	if err := t.Provider.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *DeregisterArguments) UnmarshalCBOR(r io.Reader) (err error) {
	*t = DeregisterArguments{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("DeregisterArguments: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Provider (did.DID) (struct)
		case "provider":

			{

				if err := t.Provider.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Provider: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
