//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package provider

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *Provider) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return fmt.Errorf("string in field \"endpoint\" was too long")
	}
	if err := jw.WriteString(string("endpoint")); err != nil {
		return fmt.Errorf("writing string for field \"endpoint\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Endpoint) > 8192 {
		return fmt.Errorf("string in field t.Endpoint was too long")
	}
	if err := jw.WriteString(string(t.Endpoint)); err != nil {
		return fmt.Errorf("writing string for field t.Endpoint: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("string in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("writing string for field \"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Provider: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.ReplicationWeight (int64) (int64)
	if len("replicationWeight") > 8192 {
		return fmt.Errorf("string in field \"replicationWeight\" was too long")
	}
	if err := jw.WriteString(string("replicationWeight")); err != nil {
		return fmt.Errorf("writing string for field \"replicationWeight\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.ReplicationWeight)); err != nil {
		return fmt.Errorf("writing int64 for field t.ReplicationWeight: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Weight (int64) (int64)
	if len("weight") > 8192 {
		return fmt.Errorf("string in field \"weight\" was too long")
	}
	if err := jw.WriteString(string("weight")); err != nil {
		return fmt.Errorf("writing string for field \"weight\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Weight)); err != nil {
		return fmt.Errorf("writing int64 for field t.Weight: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Provider) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Provider{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Provider: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Provider: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Provider: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Provider: string too large")
				}
				return fmt.Errorf("reading string for field Provider: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Provider: %w", err)
			}
			switch name {

			// t.Endpoint (string) (string)
			case "endpoint":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Endpoint: string too long")
						}
						return fmt.Errorf("reading string for field t.Endpoint: %w", err)
					}
					t.Endpoint = string(sval)
				}

				// t.Provider (did.DID) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

				// t.ReplicationWeight (int64) (int64)
			case "replicationWeight":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.ReplicationWeight: %w", err)
					}
					t.ReplicationWeight = int64(nval)

				}

				// t.Weight (int64) (int64)
			case "weight":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("reading int64 for field t.Weight: %w", err)
					}
					t.Weight = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Provider: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Provider: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Provider")
			}
		}
	}

	return nil
}
func (t *ListOK) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Providers ([]provider.Provider) (slice)
	if len("providers") > 8192 {
		return fmt.Errorf("string in field \"providers\" was too long")
	}
	if err := jw.WriteString(string("providers")); err != nil {
		return fmt.Errorf("writing string for field \"providers\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Providers) > 8192 {
		return fmt.Errorf("slice value in field t.Providers was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Providers: %w", err)
	}
	for i, v := range t.Providers {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Providers: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Providers: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListOK) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListOK{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for ListOK: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for ListOK: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for ListOK: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field ListOK: string too large")
				}
				return fmt.Errorf("reading string for field ListOK: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field ListOK: %w", err)
			}
			switch name {

			// t.Providers ([]provider.Provider) (slice)
			case "providers":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.Providers: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.Providers: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.Providers: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]Provider, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Providers = append(t.Providers, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.Providers: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.Providers: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for ListOK: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field ListOK: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for ListOK")
			}
		}
	}

	return nil
}
func (t *RegisterArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return fmt.Errorf("string in field \"endpoint\" was too long")
	}
	if err := jw.WriteString(string("endpoint")); err != nil {
		return fmt.Errorf("writing string for field \"endpoint\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Endpoint) > 8192 {
		return fmt.Errorf("string in field t.Endpoint was too long")
	}
	if err := jw.WriteString(string(t.Endpoint)); err != nil {
		return fmt.Errorf("writing string for field t.Endpoint: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Proofs ([]uint8) (slice)
	if len("proofs") > 8192 {
		return fmt.Errorf("string in field \"proofs\" was too long")
	}
	if err := jw.WriteString(string("proofs")); err != nil {
		return fmt.Errorf("writing string for field \"proofs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Proofs) > 2097152 {
		return fmt.Errorf("byte array in field t.Proofs was too long")
	}

	if err := jw.WriteBytes(t.Proofs); err != nil {
		return fmt.Errorf("writing bytes for field t.Proofs: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("string in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("writing string for field \"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Provider: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RegisterArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RegisterArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for RegisterArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for RegisterArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for RegisterArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field RegisterArguments: string too large")
				}
				return fmt.Errorf("reading string for field RegisterArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field RegisterArguments: %w", err)
			}
			switch name {

			// t.Endpoint (string) (string)
			case "endpoint":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Endpoint: string too long")
						}
						return fmt.Errorf("reading string for field t.Endpoint: %w", err)
					}
					t.Endpoint = string(sval)
				}

				// t.Proofs ([]uint8) (slice)
			case "proofs":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading bytes for field t.Proofs: byte array too large")
						}
						return fmt.Errorf("reading bytes for field t.Proofs: %w", err)
					}
					if len(bval) > 0 {
						t.Proofs = []uint8(bval)
					}
				}

				// t.Provider (did.DID) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for RegisterArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field RegisterArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for RegisterArguments")
			}
		}
	}

	return nil
}
func (t *DeregisterArguments) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("string in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("writing string for field \"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Provider: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *DeregisterArguments) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = DeregisterArguments{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for DeregisterArguments: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for DeregisterArguments: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for DeregisterArguments: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field DeregisterArguments: string too large")
				}
				return fmt.Errorf("reading string for field DeregisterArguments: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field DeregisterArguments: %w", err)
			}
			switch name {

			// t.Provider (did.DID) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for DeregisterArguments: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field DeregisterArguments: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for DeregisterArguments")
			}
		}
	}

	return nil
}
