name: Releaser

on:
  push:
    paths: [ 'version.json' ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  releaser:
    uses: ipdxco/unified-github-workflows/.github/workflows/releaser.yml@1822b44541e3ad073b8f9109e346ba0ddd4ce96e # v1.0
